### ISSUE TITLE
Dataset unavailable

### ISSUE THREAD

**Issue by leandroltavares** [facebook/bAbI-tasks#11]
The dataset (The SimpleQuestions dataset) provided on the project page seems to be unavailable

https://research.fb.com/downloads/babi/

That is the broken link: https://www.dropbox.com/s/tohrsllcfy7rch4/SimpleQuestions_v2.tgz

Can you please make it available again?

**Comment by jaseweston** [comment]
The link works for us -- can you try again?

**Comment by jaseweston** [comment]
It is also here:
https://s3.amazonaws.com/fair-data/parlai/simplequestions/simplequestions.tar.gz

**Comment by leandroltavares** [comment]
Thanks! Now the link is working for me too!
