### ISSUE TITLE
babi/utilities.lua line 89: is this a bug?

### ISSUE THREAD

**Issue by yujiali** [facebook/bAbI-tasks#3]
``` lua
function Grid:to_coordinates(i)
    return (i - 1) % self.width + 1, math.floor((i - 1) / 10) + 1
end
```

Should the number 10 here actually be self.width?

**Comment by bartvm** [comment]
Yes, seems like that was left over from when the `Grid` class still had a fixed size, fixed in https://github.com/facebook/bAbI-tasks/commit/0a7e05c79cdb85019e92503a0923c5112e14acbf.
