### ISSUE TITLE
Conflicting facts in generated task data

### ISSUE THREAD

**Issue by tyler7585** [facebook/bAbI-tasks#5]
I tried to generate some task data for question 15
And I got some  conflicting facts
![task15](https://cloud.githubusercontent.com/assets/20261535/17167153/7c0f177e-5416-11e6-82b2-f926e3c2a90a.png)

**Comment by tyler7585** [comment]
Why wolves and sheep are afraid of each other?.....

**Comment by alexholdenmiller** [comment]
I think we're okay with this behavior. It sounds odd with those particular animals (why would a wolf be afraid of sheep?), but less so with different pairs (tigers and lions could both be afraid of one another, or perhaps mice and elephants).
