### ISSUE TITLE
bug in logic?

### ISSUE THREAD

**Issue by asimkadav** [facebook/bAbI-tasks#7]
Hi I generated a simple example for task 4:

asim@XX:~/bAbI-tasks/: babi-tasks 4 1

1 The office is south of the garden.

2 The hallway is south of the office.

3 What is south of the hallway? office  2

I consistently see such examples being generated with incorrect answers.

**Comment by alexholdenmiller** [comment]
Thanks for catching this, @asimkadav! Added a fix to my pull request here: https://github.com/facebook/bAbI-tasks/pull/6

Will get the fix out soon.

**Comment by alexholdenmiller** [comment]
All set now, let me know if you see anything else!
