### ISSUE TITLE
Three Supporting facts requiring info from 4 facts

### ISSUE THREAD

**Issue by aferdoash** [facebook/bAbI-tasks#8]
Based on the Task name, this shouldn't be the case or am I wrong. 
I am getting stories such as -:

1 Sandra travelled to the kitchen.
2 Sandra grabbed the milk.
3 Daniel journeyed to the bedroom.
4 Sandra dropped the milk.
5 Daniel journeyed to the hallway.
6 Sandra took the milk.
7 Sandra went to the bedroom.
8 Where was the milk before the bedroom?        kitchen 1 2 6 7

**Comment by alexholdenmiller** [comment]
Thanks for reporting!

I have been able to repro, but I haven't been able to debug yet. I'll update if I can work this out.

**Comment by alexholdenmiller** [comment]
had trouble rooting out the cause, but safely removed them from the output: https://github.com/facebook/bAbI-tasks/commit/d85ad4b586cf49fa3cae26756206a8efd3434a03
